name: home_brigadier
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.6
  get_storage: 2.1.1
  flutter_svg: 2.0.9
  flutter_pin_code_fields: 2.2.0
  intl_phone_field: 3.2.0
  country_picker: 2.0.24
  table_calendar: 3.0.9
  buttons_tabbar: 1.3.8
  expandable_text: 2.3.0
  syncfusion_flutter_sliders: 24.2.4
  cached_network_image: 3.3.1
  fluttertoast: 8.2.4
  logger: 2.0.2+1
  carousel_slider: 4.2.1
  location: 5.0.3
  dio: 5.4.0
  image_picker: 1.0.7
  geolocator: 10.1.0
  geocoding: 2.1.1
  google_maps_flutter: 
  flutter_colorpicker: 1.0.3
  shimmer: 3.0.0
  font_awesome_flutter: 10.7.0
  intl: 0.18.1
  url_launcher: 6.2.4
  animated_custom_dropdown: 3.0.0
  showcaseview: 2.0.3
  flutter_spinkit: 5.2.0
  flutter_contacts: 1.1.7+1
  connectivity_plus: 5.0.2
  flip_card: 0.7.0
  patterns_canvas: 0.4.0
  http: any
  flutter_google_places: ^0.3.0
  flutter_typeahead: ^5.2.0
  lottie: ^3.0.0
  video_player: 2.8.3
  chewie: ^1.7.5
  flutter_stripe: ^10.1.1
  flutter:
    sdk: flutter
  marquee: ^2.2.3
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_launcher_icons: 0.13.1
  


flutter_launcher_icons:
  adaptive_icon_background: '#ffffff'
  android: launcher_icon
  image_path: assets/icons/launcher_icon.png
  flutter_test:
    sdk: flutter
  ios: true
  min_sdk_android: 21

flutter: 
  assets: 
    - assets/images/
    - assets/icons/
    - assets/video/
    - .env
  uses-material-design: true

