name: home_brigadier
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  get_storage: 2.1.1
  flutter_svg: 2.0.9
  flutter_pin_code_fields: 2.2.0
  intl_phone_field: 3.2.0
  country_picker: ^2.0.25
  table_calendar: ^3.1.1
  buttons_tabbar: ^1.3.9
  expandable_text: 2.3.0
  syncfusion_flutter_sliders: ^25.1.35
  cached_network_image: 3.3.1
  fluttertoast: ^8.2.5
  carousel_slider: 4.2.1
  location: ^6.0.2
  dio: ^5.4.2
  image_picker: ^1.1.1
  geolocator: ^12.0.0
  geocoding: ^3.0.0
  google_maps_flutter: any
  shimmer: 3.0.0
  font_awesome_flutter: 10.7.0
  intl: ^0.19.0
  url_launcher: ^6.2.5
  animated_custom_dropdown: 3.0.0
  showcaseview: ^2.0.3
  flutter_spinkit: ^5.2.1
  flutter_contacts: 1.1.7+1
  connectivity_plus: ^6.0.1
  patterns_canvas: 0.4.0
  http: any
  flutter_google_places: ^0.3.0
  lottie: ^3.0.0
  video_player: ^2.8.6
  flutter_stripe: ^10.1.1
  marquee: ^2.2.3
  flutter_dotenv: ^5.1.0
  dartx: 1.2.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^4.0.0
  flutter_launcher_icons: 0.13.1
  logger: ^2.2.0
  flutter_test: 
    sdk: flutter

flutter_launcher_icons: 
  android: ic_launcher
  image_path: assets/launcher/ic_launcher.png
  ios: true
  min_sdk_android: 21
  remove_alpha_ios: true

flutter: 
  assets: 
    - assets/images/
    - assets/icons/
    - assets/video/
    - .env
    - assets/launcher/
  uses-material-design: true

