on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main
      - usman
name: "Build & Release"
jobs:
  build:
    name: Build & Release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        flutter: [ 3.19.6 ]  # Specify your desired Flutter version
        java: [ 19.0.2 ]         # Specify your desired Java version

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # You can choose other distributions like 'zulu', 'adopt', etc.
          java-version: ${{ matrix.java }}

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ matrix.flutter }}

      - name: Flutter Clean
        run: flutter clean

      - name: Install dependencies
        run: flutter pub get
#    steps:
#      - uses: actions/checkout@v3
#      - uses: actions/setup-java@v3
#        with:
#          java-version: '19'
#          distribution: 'temurin'
#
#      - uses: subosito/flutter-action@v2
#        with:
#          channel: 'stable'
#          flutter-version: "3.19.6"
#          architecture: x64

      - run: flutter clean
      - run: flutter build apk --release --split-per-abi
#      - run: |
#          flutter build ios --no-codesign
#          cd build/ios/iphoneos
#          mkdir Payload
#          cd Payload
#          ln -s ../Runner.app
#          cd ..
#          zip -r app.ipa Payload
      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/release/*,build/ios/iphoneos/app.ipa"
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.TOKEN }}
